spring:
  application:
    name: novabank-v3

  datasource:
    url: jdbc:postgresql://localhost:5432/NovaBank
    username: postgres
    password: sF0I+S2K2X4c
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: novabank-super-secret-key-para-jwt-minimo-32-chars
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs